---
  - hosts: webservers
    become: true
    tasks:
      - name: update all packages to the latest version
        dnf: name=* state=latest

      - name: install httpd webserver
        dnf: name=httpd state=present

      - name: install git
        dnf: name=git state=present

      - name: delete original index.html file
        file: path=/var/www/html/index.html state=absent

      - name: create directory for github to use
        file:
          path: /var/www/github
          state: directory

      - name: download github repository
        git:
          repo: 'https://github.com/MajinBeans/Ansible_101.git'
          dest: /var/www/github

      - name: copy index.html into the /var/www/html folder
        command: mv /var/www/github/index.html /var/www/html
        notify: start httpd

    handlers:
      - name: start httpd
        service: name=httpd state=started
