---
  - hosts: local
    vars:
      playbooks_location: "/home/vagrant/newfolder/playbooks"
    tasks:
      - name: get the list of all playbooks containing the word 'httpd'
        shell: ls {{ playbooks_location }} | grep httpd
        register: playbooks_with_httpd

      - name: list out all playbooks containing the word httpd
        debug:
          msg: "{{ playbooks_with_httpd  }}"
