---
  - hosts: webservers
    become: true
    tasks:
      - name: create new index/html file
        lineinfile:
          create: yes
          path: /var/www/html/index.html
          line: <html>Hello from server1</html>
        notify: start httpd

    handlers:
      - name: start httpd
        service: name=httpd state=started
