---
  - hosts: local
    become: true
    vars:
      server1: "{{ lookup('csvfile', 'server1 file=../files/assignment_hosts.csv delimiter=, col=2') }}"
      server2: "{{ lookup('csvfile', 'server2 file=../files/assignment_hosts.csv delimiter=, col=2') }}"

    vars_files:
      - ../files/addresses.yml

    tasks:
      - name: display addresses of server1 and server2
        debug:
          msg:
            - "server1: {{ server1 }}"
            - "server2: {{ server2 }}"

      - name: List addresses with index
        debug:
          msg: "{{ idx }}: {{ item }}"
        loop: "{{addresses}}"
        loop_control:
          index_var: idx
