---
  - hosts: local
    become: true
    vars:
      names: [Marc, Dean, John, Patrick]

    vars_files:
      - ../files/list.yml

    tasks:
      - name: Print out the days of the week
        debug:
          msg: "{{ item }}"
        loop:
          - Sunday
          - Monday
          - Tuesday
          - Wednesday
          - Thursday
          - Friday
          - Saturday

      - name: Print a list of names
        debug:
          msg: "{{ my_idx }}: {{ item }}"
        loop: "{{names}}"
        loop_control:
          index_var: my_idx

      - name: Print a list of numbers
        debug:
          msg: "{{ item }}"
        loop: "{{directions}}"
