---
  - hosts: webservers
    become: true
    tasks:
      - name: install httpd webserver
        dnf: name=httpd state=present

      - name: delete original index.html file
        file: path=/var/www/html/index.html state=absent
