---
  - hosts: webservers
    become: true
    tasks:
      - name: update all packages to the latest version
        dnf: name=* state=latest

      - name: install httpd webserver
        dnf: name=httpd state=present

      - name: install git
        dnf: name=git state=present

      - name: delete original index.html file
        file: path=/var/www/html/index.html state=absent
        tags: tag-2

      - name: create new index.html file
        lineinfile:
          create: yes
          path: /var/www/html/index.html
          line: <html>Tag Number One</html
        tags: tag-1

      - name: create new index.html file
        lineinfile:
          create: yes
          path: /var/www/html/index.html
          line: <html>Tag Number Two</html>
        tags: tag-2

      - name: restart httpd
        service: name=httpd state=restarted
        tags: tag-2
