---
 - name: update all packages to the latest version
   dnf: name=* state=latest

 - name: install httpd webserver
   dnf: name=httpd state=present

 - name: delete old index.html file
   file: path={{ filepath }} state=absent

 - name: create a simple html file
   lineinfile:
    create: yes
    path: "{{ filepath }}"
    line: <html>{{ message }}</html
   notify: start httpd
